
CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN,
  PRICE DOUBLE
);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("EGGS", FALSE, TRUE, FALSE, TRUE, 1.50);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BREAD", FALSE, TRUE, TRUE, FALSE, 3.20);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BEEF PATTY", FALSE, FALSE, FALSE, TRUE, 5.00);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("LETTUCE", FALSE, TRUE, TRUE, TRUE, 0.99);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("YOGHURT", TRUE, TRUE, FALSE, TRUE, 1.29);

SELECT NAME FROM INGREDIENT;
SELECT NAME, PRICE FROM INGREDIENT;
SELECT * FROM INGREDIENT
ORDER BY NAME;
SELECT * FROM INGREDIENT
ORDER BY GLUTEN_FREE DESC;
