CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255)
);
CREATE TABLE ORDER (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_COST DECIMAL(10,2)
);


SELECT * FROM CUSTOMER
LEFT JOIN ORDER ON CUSTOMER.CUSTOMER_ID = ORDER.CUSTOMER_ID;

SELECT * FROM CUSTOMER
LEFT JOIN ORDER ON CUSTOMER.CUSTOMER_ID = ORDER.CUSTOMER_ID
WHERE ORDER.CUSTOMER_ID IS NULL;

SELECT * FROM CUSTOMER
INNER JOIN ORDER ON CUSTOMER.CUSTOMER_ID = ORDER.CUSTOMER_ID;

SELECT * FROM CUSTOMER
RIGHT JOIN ORDER ON CUSTOMER.CUSTOMER_ID = ORDER.CUSTOMER_ID;

SELECT * FROM CUSTOMER
RIGHT JOIN ORDER ON CUSTOMER.CUSTOMER_ID = ORDER.CUSTOMER_ID
WHERE CUSTOMER.CUSTOMER_ID IS NULL;
