
CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE, 
  CALORIES INT
);

CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN,
  PRICE DOUBLE
);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("EGGS", FALSE, TRUE, FALSE, TRUE, 1.50);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BREAD", FALSE, TRUE, TRUE, FALSE, 3.20);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BEEF PATTY", FALSE, FALSE, FALSE, TRUE, 5.00);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("LETTUCE", FALSE, TRUE, TRUE, TRUE, 0.99);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("YOGHURT", TRUE, TRUE, FALSE, TRUE, 1.29);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);

CREATE TABLE CHEAP_MEAL AS
SELECT * FROM MEAL WHERE PRICE < 15;

CREATE TABLE VEGAN_INGREDIENT AS 
SELECT * FROM INGREDIENT WHERE FALSE;

INSERT INTO VEGAN_INGREDIENT 
SELECT * FROM INGREDIENT WHERE VEGAN;

CREATE VIEW EXPENSIVE_MEAL AS
SELECT * FROM MEAL WHERE PRICE > 15;

CREATE VIEW LACTOSE_FREE_INGREDIENT AS
SELECT * FROM INGREDIENT WHERE !CONTAINS_LACTOSE;

CREATE TABLE HIGH_CALORIE_MEAL AS
SELECT * FROM MEAL WHERE CALORIES > 650;
