
CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE, 
  CALORIES INT
);

CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN,
  PRICE DOUBLE
);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("EGGS", FALSE, TRUE, FALSE, TRUE, 1.50);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BREAD", FALSE, TRUE, TRUE, FALSE, 3.20);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("BEEF PATTY", FALSE, FALSE, FALSE, TRUE, 5.00);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("LETTUCE", FALSE, TRUE, TRUE, TRUE, 0.99);

INSERT INTO INGREDIENT(NAME, CONTAINS_LACTOSE ,VEGETARIAN, VEGAN, GLUTEN_FREE, PRICE)
VALUES("YOGHURT", TRUE, TRUE, FALSE, TRUE, 1.29);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);

CREATE TABLE MEAL_ORDER (
  TIME_MEAL_ORDERED TIMESTAMP DEFAULT NOW(),
  MEAL_NAME VARCHAR(255)
);
  
    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (NOW(), 'Spaghetti Bolognese');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 1 HOUR), 'Grilled Chicken Sandwich');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 2 HOUR), 'Pesto Pasta');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 3 HOUR), 'Pesto Pasta');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 4 HOUR), 'Grilled Chicken Sandwich');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 5 HOUR), 'Pesto Pasta');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 6 HOUR), 'Spaghetti Bolognese');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 7 HOUR), 'Pesta Pasta');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 8 HOUR), 'Pesto Pasta');

    INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME) 
    VALUES (DATE_ADD(NOW(), INTERVAL 9 HOUR), 'Spaghetti Bolognese');
    
CREATE TABLE NUMBER (
  NUM DOUBLE
);

INSERT INTO NUMBER(NUM)
VALUES (46515616.65483),
       (1546512515345.46467),
       (1254896321.4978632);
























SELECT CONCAT(NAME, " ", PRICE) AS NAME_AND_PRICE,         # unisce in un'unica colonna i valori di due campi
 LOWER(NAME) AS LOWERCASE_NAME,                            # stampa i valori in minuscolo
 UPPER(NAME) AS UPPERCASE_NAME,                            # stampa i valori in maiuscolo
 TRIM(NAME) AS TRIM_NAME,                                  # elimina gli spazi in eccesso
 LENGTH(NAME) AS NAME_LENGTH,                              # ritorna la lunghezza della stringa
 SUBSTRING(NAME,1,3) AS SHORT_NAME,                        # estrae una parte della stringa, possiamo selezionare il carattere di partenza e la lunghezza della stringa finale
 ROUND(PRICE, 1) AS ROUNDED_PRICE                          # arrotonda ad un numero di cifre decimali a nostra scelta
 FROM MEAL;
 SELECT DATE_ADD(TIME_MEAL_ORDERED, INTERVAL 10 MINUTE) AS SHIFTED_AHEAD_TIME_MEAL_ORDERED,  # aggiunge un intervallo di tempo alla data
 DATE_SUB(TIME_MEAL_ORDERED, INTERVAL 10 MINUTE) AS SHIFTED_BACK_TIME_MEAL_ORDERED  # sottrae un intervallo di tempo alla data
 FROM MEAL_ORDER; 
 SELECT FORMAT(NUM, 2) AS FORMATTED_NUM   # formatta il numero separando ogni # cifre con il . e arrotonda ad un numero di cifre decimali a mia scelta
 FROM NUMBER;
 
 

